# Generated by Django 2.2.6 on 2019-10-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20191008_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
