# Generated by Django 2.2.6 on 2019-10-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20191008_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
